# Generated by Django 3.2.12 on 2022-02-19 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220219_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_list', to='api.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_list_participant', to='api.participant')),
                ('should_give', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_list_should_give', to='api.participant')),
            ],
        ),
    ]
