# Generated by Django 3.2.12 on 2022-02-19 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_giftlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_draw', to='api.event')),
            ],
        ),
    ]
