---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: secret-santa-prod
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: secret-santa-prod
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: registry.gitlab.com/louismarie/secret-santa/backend:3d22bc5
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
