apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: secret-santa-argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:admin
  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.admin: apiKey, login
  # disables user. User is enabled by default
  accounts.admin.enabled: "true"
