---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secret-santa-prod
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: secret-santa-prod
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend
          image: registry.gitlab.com/louismarie/secret-santa/frontend:3d22bc5
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
