name: Deploy to tiragecadeaux.com
'on':
  push:
    branches:
      - master
jobs:
  build_deploy_front:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name and sha
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Gitlab registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: front
          push: true
          tags: registry.gitlab.com/louismarie/secret-santa/frontend:${{ steps.vars.outputs.branch }},registry.gitlab.com/louismarie/secret-santa/frontend:${{ steps.vars.outputs.sha_short }}
      - name: Sync ArgoCD Application frontend
        uses: omegion/argocd-app-actions@master
        with:
          address: argo.tiragecadeaux.com
          token: ${{ secrets.ARGOCD_TOKEN }}
          appName: "prod-frontend"
  build_deploy_back:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name and sha
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Gitlab registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: back
          push: true
          tags: registry.gitlab.com/louismarie/secret-santa/backend:${{ steps.vars.outputs.branch }},registry.gitlab.com/louismarie/secret-santa/backend:${{ steps.vars.outputs.sha_short }}
      - name: Sync ArgoCD Application backend
        uses: omegion/argocd-app-actions@master
        with:
          address: argo.tiragecadeaux.com
          token: ${{ secrets.ARGOCD_TOKEN }}
          appName: "prod-backend"
